### ISSUE TITLE
Need start-up script for initializing virtual environment and web server

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSAX#2]
Since developers using the SDK will need to fire up first a virtual environment and then a web server every time that they want to do work, we should make a script for this. Something like::

      . ~/envs/sdk/bin/activate
      cd ~/dev/xblock-sdk
      python manage.py runserver

This would probably go in /OpenDSAX.

We might also want scripts for firing up the dev stack.

**Comment by cashaffer** [comment]
Not so fast! :)

The scripts are working for my on Windows, both for the cmd.exe shell with the run_sdk.bat script, and also with bash and the run_sdk script.

So far, I am not having any luck with getting this to run on my Linux machine. We should talk about this.

**Comment by hosamshahin** [comment]
What was the error? I tried it on algoviz-beta6 and it was working fine.

**Comment by cashaffer** [comment]
As we determined today, the problem boils down to my needing the script to use "sudo" when invoking the web server. I don't know for sure if the problem is caused by a badly installed version of virtualenv and/or pip, or if this is going to be a common problem for Linux users. For now, we can leave this as is. Thanks!
