### ISSUE TITLE
Top Navigation Bar xblock in book generation

### ISSUE THREAD

**Issue by acbart** [OpenDSA/OpenDSAX#5]
This needs to be created.

**Comment by acbart** [comment]
@hosamshahin - do you know where I can get a sample of the xblock xml I should generate?

**Comment by hosamshahin** [comment]
Go to opendsax.cc.vt.edu:18010 (verified@example.com/edx) export "Online Education" course and you can find it there.

**Comment by acbart** [comment]
Wait, sorry, I was confused. For some reason, I keep thinking that we will be creating a specific XBlock to handle this, instead of just creating some simple markup to render previous and next links.

**Comment by hosamshahin** [comment]
Actually topnav is a Content xblock having a contnet_type="topnav"

**Comment by acbart** [comment]
So it will look for an html file based on its url_name inside the xblock-content/content/public/html folder. So I should be creating e.g., quicksort-nav.html as part of my build process, and letting it get sent there during the make process?

**Comment by hosamshahin** [comment]
No, you have to initialize it like this:
<content url_name="929a4429ccbc45b19c56e76cd3a729cf" xblock-family="xblock.v1" contnet_type="topnav" next_link="" prev_link=""  next_name=""  prev_name=""  toc_link=""/>

Where :
_link is the physical link which will direct student to next/previous module
_name  is the like name
toc_link  the like to TOC page

**Comment by acbart** [comment]
Yeah, I see what you mean: https://github.com/OpenDSA/OpenDSAX/blob/master/xblocks/xblock-content/content/content.py#L17

Thanks!

**Comment by hosamshahin** [comment]
Sorry, it seems I've confused you. I added the xml markup to the previous comment but for some reason md did't show it. But now I've updated the comment having the xml markup in double backticks and it is shown now. So back to the code the "_type" I want in the xml is the content_type 
https://github.com/OpenDSA/OpenDSAX/blob/master/xblocks/xblock-content/content/content.py#L57
not the XBlock_type https://github.com/OpenDSA/OpenDSAX/blob/master/xblocks/xblock-content/content/content.py#L17

**Comment by acbart** [comment]
No, I got what you meant. I linked to the start of that section just to show I saw what the other fields were labelled. Thanks for clarifying though, it's good to see!

**Comment by hosamshahin** [comment]
Good, and since we are discussing the navigation, you should have noticed that the TOC page does not have prev link and the last module page does not have next link. So as a general rule if you want to remove the any like all together just set _link to empty string "".

**Comment by acbart** [comment]
c008a4d916b1ad7da07260a9c9c8487e71c2f2f8
